// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  protoc-gen-go v1.28.1 // Example version
//  protoc        v3.21.12 // Example version
// source: echonet_v3_core.proto

package corev3 // Corresponds to ';corev3' in go_package

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for different types of interactions that can be recorded.
type InteractionType int32

const (
	InteractionType_INTERACTION_TYPE_UNSPECIFIED InteractionType = 0
	InteractionType_INTERACTION_TYPE_CREATE_POST InteractionType = 1
	InteractionType_INTERACTION_TYPE_COMMENT     InteractionType = 2
	InteractionType_INTERACTION_TYPE_REACTION    InteractionType = 3
	InteractionType_INTERACTION_TYPE_SHARE       InteractionType = 4
	InteractionType_INTERACTION_TYPE_FOLLOW      InteractionType = 5
	InteractionType_INTERACTION_TYPE_MENTION     InteractionType = 6
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "INTERACTION_TYPE_UNSPECIFIED",
		1: "INTERACTION_TYPE_CREATE_POST",
		2: "INTERACTION_TYPE_COMMENT",
		3: "INTERACTION_TYPE_REACTION",
		4: "INTERACTION_TYPE_SHARE",
		5: "INTERACTION_TYPE_FOLLOW",
		6: "INTERACTION_TYPE_MENTION",
	}
	InteractionType_value = map[string]int32{
		"INTERACTION_TYPE_UNSPECIFIED": 0,
		"INTERACTION_TYPE_CREATE_POST": 1,
		"INTERACTION_TYPE_COMMENT":     2,
		"INTERACTION_TYPE_REACTION":    3,
		"INTERACTION_TYPE_SHARE":       4,
		"INTERACTION_TYPE_FOLLOW":      5,
		"INTERACTION_TYPE_MENTION":     6,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

// Represents a piece of content on the DigiSocialBlock platform.
type NexusContentObjectV1 struct {
	state protoimpl.MessageState
	sizeCache protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContentId          string  `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ContentHash        []byte  `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	TimestampCreatedMs int64   `protobuf:"varint,3,opt,name=timestamp_created_ms,json=timestampCreatedMs,proto3" json:"timestamp_created_ms,omitempty"`
	AuthorDid          string  `protobuf:"bytes,4,opt,name=author_did,json=authorDid,proto3" json:"author_did,omitempty"`
	ContentType        string  `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MetadataJsonStr    *string `protobuf:"bytes,6,opt,name=metadata_json_str,json=metadataJsonStr,proto3,oneof" json:"metadata_json_str,omitempty"`
	LastModifiedMs     int64   `protobuf:"varint,10,opt,name=last_modified_ms,json=lastModifiedMs,proto3" json:"last_modified_ms,omitempty"`
	ParentContentId    string  `protobuf:"bytes,11,opt,name=parent_content_id,json=parentContentId,proto3" json:"parent_content_id,omitempty"`
}

func (x *NexusContentObjectV1) Reset() {
	*x = NexusContentObjectV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_echonet_v3_core_proto_msgTypes[0] // Placeholder index
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NexusContentObjectV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NexusContentObjectV1) ProtoMessage() {}

func (x *NexusContentObjectV1) GetContentId() string { if x != nil { return x.ContentId } return "" }
func (x *NexusContentObjectV1) GetContentHash() []byte { if x != nil { return x.ContentHash } return nil }
func (x *NexusContentObjectV1) GetTimestampCreatedMs() int64 { if x != nil { return x.TimestampCreatedMs } return 0 }
func (x *NexusContentObjectV1) GetAuthorDid() string { if x != nil { return x.AuthorDid } return "" }
func (x *NexusContentObjectV1) GetContentType() string { if x != nil { return x.ContentType } return "" }
func (x *NexusContentObjectV1) GetMetadataJsonStr() string { if x != nil && x.MetadataJsonStr != nil { return *x.MetadataJsonStr } return "" }
func (x *NexusContentObjectV1) GetLastModifiedMs() int64 { if x != nil { return x.LastModifiedMs } return 0 }
func (x *NexusContentObjectV1) GetParentContentId() string { if x != nil { return x.ParentContentId } return "" }

// Represents a user profile and state on the DigiSocialBlock platform.
type NexusUserObjectV1 struct {
	state protoimpl.MessageState
	sizeCache protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserDid                 string  `protobuf:"bytes,1,opt,name=user_did,json=userDid,proto3" json:"user_did,omitempty"`
	ProfileDataHash         []byte  `protobuf:"bytes,2,opt,name=profile_data_hash,json=profileDataHash,proto3" json:"profile_data_hash,omitempty"`
	ReputationScoreInt64    int64   `protobuf:"varint,3,opt,name=reputation_score_int64,json=reputationScoreInt64,proto3" json:"reputation_score_int64,omitempty"`
	PopStateSummaryHash     []byte  `protobuf:"bytes,4,opt,name=pop_state_summary_hash,json=popStateSummaryHash,proto3" json:"pop_state_summary_hash,omitempty"`
	RegistrationTimestampMs int64   `protobuf:"varint,5,opt,name=registration_timestamp_ms,json=registrationTimestampMs,proto3" json:"registration_timestamp_ms,omitempty"`
	LastActiveTimestampMs   int64   `protobuf:"varint,6,opt,name=last_active_timestamp_ms,json=lastActiveTimestampMs,proto3" json:"last_active_timestamp_ms,omitempty"`
	PublicKeyPem            *string `protobuf:"bytes,7,opt,name=public_key_pem,json=publicKeyPem,proto3,oneof" json:"public_key_pem,omitempty"`
	IsActive                bool    `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}
func (x *NexusUserObjectV1) Reset() { /* ... */ }
func (x *NexusUserObjectV1) String() string { return protoimpl.X.MessageStringOf(x) }
func (*NexusUserObjectV1) ProtoMessage() {}
func (x *NexusUserObjectV1) GetUserDid() string { if x != nil { return x.UserDid } return "" }
// ... other getters for NexusUserObjectV1 ...

// Records a specific interaction event on the platform.
type NexusInteractionRecordV1 struct {
	state protoimpl.MessageState
	sizeCache protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InteractionId             string          `protobuf:"bytes,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	InteractionType           InteractionType `protobuf:"varint,2,opt,name=interaction_type,json=interactionType,proto3,enum=echonet.core.v3.InteractionType" json:"interaction_type,omitempty"`
	TimestampMs               int64           `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	ActorDid                  string          `protobuf:"bytes,4,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	SubjectContentId          *string         `protobuf:"bytes,5,opt,name=subject_content_id,json=subjectContentId,proto3,oneof" json:"subject_content_id,omitempty"`
	TargetUserDid             *string         `protobuf:"bytes,6,opt,name=target_user_did,json=targetUserDid,proto3,oneof" json:"target_user_did,omitempty"`
	InteractionMetadataJsonStr *string         `protobuf:"bytes,7,opt,name=interaction_metadata_json_str,json=interactionMetadataJsonStr,proto3,oneof" json:"interaction_metadata_json_str,omitempty"`
	InteractionDataHash       []byte          `protobuf:"bytes,8,opt,name=interaction_data_hash,json=interactionDataHash,proto3" json:"interaction_data_hash,omitempty"`
}
func (x *NexusInteractionRecordV1) Reset() { /* ... */ }
func (x *NexusInteractionRecordV1) String() string { return protoimpl.X.MessageStringOf(x) }
func (*NexusInteractionRecordV1) ProtoMessage() {}
func (x *NexusInteractionRecordV1) GetInteractionId() string { if x != nil { return x.InteractionId } return "" }
// ... other getters for NexusInteractionRecordV1 ...

// Represents a Proof-of-Work (PoW) attestation by a witness node.
type WitnessProofV1 struct {
	state protoimpl.MessageState
	sizeCache protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WitnessDid        string `protobuf:"bytes,1,opt,name=witness_did,json=witnessDid,proto3" json:"witness_did,omitempty"`
	AttestedDataHash  []byte `protobuf:"bytes,2,opt,name=attested_data_hash,json=attestedDataHash,proto3" json:"attested_data_hash,omitempty"`
	TimestampMs       int64  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Nonce             int64  `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	PreviousProofHash []byte `protobuf:"bytes,5,opt,name=previous_proof_hash,json=previousProofHash,proto3" json:"previous_proof_hash,omitempty"`
	Signature         string `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}
func (x *WitnessProofV1) Reset() { /* ... */ }
func (x *WitnessProofV1) String() string { return protoimpl.X.MessageStringOf(x) }
func (*WitnessProofV1) ProtoMessage() {}
func (x *WitnessProofV1) GetWitnessDid() string { if x != nil { return x.WitnessDid } return "" }
// ... other getters for WitnessProofV1 ...

// Placeholder for file descriptor and other generated boilerplate
var file_echonet_v3_core_proto_msgTypes = make([]protoimpl.MessageInfo, 4) // 4 messages
// ... more boilerplate ...

func init() { /* file_echonet_v3_core_proto_init() */ } // Placeholder
